### ISSUE TITLE
Comet - Extend REST API

### ISSUE THREAD

**Issue by amarbajric** [fiware-austria/SCDP#82] opened 2019-01-23 15:05 UTC
Add new REST API to comet where we can:
- request multiple attributes from a single sensor
- request data from a sensor with selected attributes (with geo data included)

**Comment by apruitg** [comment] 2019-02-27 15:38
Duplicate of #78

**Closed as completed** 2019-02-27 15:38 UTC
Labels: production

**Comment by amarbajric** [comment] 2019-03-06 23:16
Feature description for the v2.5.0 release can be found [here](https://github.com/amarbajric/fiware-sth-comet/blob/ippr-dev/doc/release-info/Comet_v2.5.0_Feature_Extensions.md)
